### ISSUE TITLE
yarn dev command is not working in node 16 version.

### ISSUE THREAD

**Issue by nomandhoni-cs** [reactjs/bn.reactjs.org#206]
I have to downgrade to 13/ 14/ 15/

**Comment by AlSajid** [comment]
please, someone upgrade the project to latest node version.

**Comment by shakib609** [comment]
We have updated the `main` branch with latest updates from `reactjs.org` repository. It is working as expected from my end. Can you guys try again after pulling the latest changes from `main`?
@nomandhoni-cs @AlSajid

**Comment by nomandhoni-cs** [comment]
@shakib609 Thanks, now it's working with the latest version of Node.js

I want to contribute in the docs, do I have to get assigned in specific task, before I start contributing.

**Comment by shakib609** [comment]
Hi @nomandhoni-cs , you can check #1 to see the pending translation tasks. You can pick any of them up. I would recommend going for one of the core pages first if possible.

Closing this issue, as it's resolved. Thanks for pointing out. 🙌
